################################################################################
################################################################################
# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

################################################################################
# Site settings

title: FSA Design System
email: France.Rupert@gmail.com
description: Design System site for USDA Farm Service Agency digital products
name: "fsa-design-system"
baseurl: "/fsa-design-system/" # the subpath of your site, e.g. /blog
url: "https://usda-fsa.github.io" # the base hostname & protocol for your site
twitter_username: francisrupert
github_username:  usda-fsa
permalink: none
github_repository_url: https://github.com/USDA-FSA/fsa-design-system
fsa-style_version: 2.1.7

# Site key assets
stylesheets:
  - css/fsa-design-system.min.css

scripts:
  - js/fsa-design-system.min.js

################################################################################
# Ignore specific items from building

exclude:
  - node_modules
  - package.json
  - Gruntfile.js
  - README.md
  - vendor
